name: Deploy to Server

on:
  push:
    branches:
      - master  # Trigger deployment only on pushes to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      env:
        SSH_KEY: ${{ secrets.KEY }}
        SSH_PASSPHRASE: ${{ secrets.PASSPHRASE }}
      run: |
        mkdir -p ~/.ssh
        echo "$KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        echo "$PASSPHRASE" | ssh-add ~/.ssh/id_rsa

    - name: Run deployment script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /path/to/your/project
          git pull origin master
          # Add any other commands you need to run for deployment

    - name: Cleanup SSH
      run: ssh-agent -k
